### ISSUE TITLE
IPF files need to start with a unicode character

### ISSUE THREAD

**Issue by laurencee** [Xanaxiel/ToS-Addons#10]
You seem to have a letter h at the start of your ipf file names (at least that's what it is when using 7zip 15.08), in order for them not to be removed at TOS startup they need to start with a unicode character name.

**Comment by ghost** [comment]
Nah, there's no h. 7zip just can't handle unicode and fucks it up. It's `☃tooltiphelper.ipf`. Just use windows zip to unzip.

**Comment by laurencee** [comment]
Interesting, 7zip handles unicode fine in some zips but not others.

Maybe it's due to zip format used in the first place. I might see if I can raise a bug on 7zip forum.

**Comment by TehSeph** [comment]
@Excrulon No, there **is** definitely an `h` there, he is right.
![h](http://i.imgur.com/a2ftZAh.png)

@laurencee It has to do with how the zip is packaged, not extracted. 7zip should be able to handle unicode fine. Winzip is the only one that I know of that might have problems. @Xanaxiel more than likely has compression enabled when creating his zips instead of just storing them in an archive. When a zip is compressed, weird things happen to unicode. If the files are just stored in a zip and not compressed, they should retain the unicode just fine. Either way, considering you seem to understand that they need the unicode character, just manually add them for now. :smiley:

**Comment by laurencee** [comment]
Updated to 7zip 16.02 and it works fine now: http://www.7-zip.org/download.html

![image](https://cloud.githubusercontent.com/assets/3850553/15631657/c3b95b94-25b7-11e6-88bc-77e895903892.png)

**Comment by TehSeph** [comment]
huh.

**Comment by ghost** [comment]
@TehSeph Then the program you're using to extract it can't handle unicode as well. There's an h for me when I extract with 7zip. Shows as `☃tooltiphelper.ipf` when I use windows (10).

**Comment by laurencee** [comment]
@TehSeph  Maybe there's an update to WinRAR that sorts out the issue for you.

**Comment by TehSeph** [comment]
Yeah, looks like 7zip and Windows10 can handle the compression just fine.
Damn. Time to see about a Winrar update... Probably doesn't help that I'm on 4.0 and latest is 5.4.

**Comment by TehSeph** [comment]
Yep. That fixed it for me as well. I've just been zipping mine uncompressed, and probably will keep doing so. Addons aren't that big, and it saves other users from this headache.

**Comment by laurencee** [comment]
Well given 7zip is completely free there's no reason people shouldn't update it if they happen to be using that.

Just have to keep this in mind as I'm sure this will come up again in the future.
