### ISSUE TITLE
[request] Check if normal itens are registered.

### ISSUE THREAD

**Issue by plex-tos** [Xanaxiel/ToS-Addons#11]
Hi Xanaxiel,

If possible please add if normal itens(weapons, armors, bracelets) are registered too.. as the recipes it would help a lot!!

**Comment by Xanaxiel** [comment]
I didn't add the other items as they become registered the moment you obtain them (when you see that "Journal updated" message popping up when you loot an item), basically what's in your inventory is most probably registered **but** the recipes are an exception since sometimes they require to be manually registered. I don't think it's needed though. Besides, if you're aiming for score, you gotta be filthy rich, as on equipment alone, the score differs for each enhancement level you have (of course the higher enhancement, the higher score).
